<a href="<?php echo $this->url('home') ?>">Retour</a>
<h1> <span class="zf-green"><?php echo $training->getTitle();?> </span> Training</h1>

    <p>
       <?php echo  $training->getDescription(); ?>
    </p>
    <sapn><?php echo "Students Number :".$training->getStudentsNbr(); ?></sapn><br/>

    <span> Start Date: <?php echo $training->getStartDate()->format('d/m/y'); ?></span><br/>
    <span> Start Date:<?php echo $training->getEndDate()->format('d/m/y'); ?></span><br/>
    <span> Duration:<?php echo $training->duration(); ?> Jours </span><br/>
    <span> Training:<?php
        echo $this->TrainingHelper()->getStatus($training->getStartDate(),$training->getEndDate());
        ?>  </span><br/>
    <h3>Students List</h3>
    <span> <?php $students = $training->getStudents();
    $i=1;
    foreach ($students as $student){
        echo $i."-".$student->getFirstName()." ".$student->getLastName()."<br/>";
        $i++;
    }
    ?> </span><br/>
