    <?php
    $i=1;

    ?>
    <H3><?php echo count($trainings); ?> Trainings Available</H3>
    <?php
    foreach ($trainings as $training){
        $url = $this->url('training',['id'=>($training->getId())]);
        ?>
        <a href="<?php echo $url; ?>">
    <?php
    echo $i."-".$training->getTitle()."<br/>";
        $i++;
    }
    ?>
        </a>
    <h3><?php echo count($student_list); ?> Students</h3>
    <a href="<?php echo $this->url('studentslist');?>"> Students List</a>



